# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('dyngame_rcpp_hello_world', PACKAGE = 'dyngame')
}

C_get_from_pos <- function(m, pos_k) {
    .Call('dyngame_C_get_from_pos', PACKAGE = 'dyngame', m, pos_k)
}

